services:
  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    container_name: litellm
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      STORE_MODEL_IN_DB: ${STORE_MODEL_IN_DB}
      LITELLM_MASTER_KEY: ${LITELLM_MASTER_KEY}
      UI_BASE_URL: ${UI_BASE_URL}
      MCP_TOOL_PREFIX_SEPARATOR: ":"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    command: ["--config", "/app/config.yaml"]
    networks:
      - vibes-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

networks:
  vibes-network:
    external: true