services:
  litellm-proxy:
    image: ghcr.io/berriai/litellm:main-latest
    container_name: litellm-proxy
    environment:
      # Core configuration - using Supabase PostgreSQL
      DATABASE_URL: ${DATABASE_URL}
      STORE_MODEL_IN_DB: ${STORE_MODEL_IN_DB}
      LITELLM_MASTER_KEY: ${LITELLM_MASTER_KEY}
      
      # UI configuration
      UI_BASE_URL: ${UI_BASE_URL}
      
      # Optional: Enable Supabase logging callbacks
      # LITELLM_SUCCESS_CALLBACK: "supabase"
      # LITELLM_FAILURE_CALLBACK: "supabase"
    ports:
      - "${LITELLM_PROXY_PORT}:4000"
    networks:
      - supabase_default
      - vibes-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    stdin_open: true
    tty: true

networks:
  supabase_default:
    external: true
  vibes-network:
    external: true
