version: '3.8'

services:
  azure-mcp-server:
    image: vibes/mcp-azure-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: azure-mcp-server
    restart: unless-stopped
    environment:
      # Azure Authentication - set these in .env file
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_SUBSCRIPTION_ID=${AZURE_SUBSCRIPTION_ID}
      
      # Alternative: Managed Identity (for Azure VMs)
      # - AZURE_USE_MANAGED_IDENTITY=true
      
      # MCP Server Configuration
      - MCP_SERVER_NAME=azure-mcp-server
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    
    ports:
      - "8080:8080"
    
    # Mount Azure config if using Azure CLI authentication (commented out for containerized env)
    # volumes:
    #   - ~/.azure:/root/.azure:ro
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: vibes-network
    external: true
