services:
  mcp-middleware-server:
    image: vibes/mcp-middleware-server:latest
    build: .
    container_name: mcp-middleware-server
    restart: unless-stopped
    ports:
      - "5001:5001"  # SSE endpoint port
    environment:
      - MCP_SERVER_NAME=mcp-middleware-server
      - PORT=5001
    
    # Health check for SSE endpoint
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  default:
    name: vibes-network
    external: true
