services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-litellm-db.sh:/docker-entrypoint-initdb.d/init-litellm-db.sh:ro
    networks:
      - vibes-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "${POSTGRES_HOST}:${POSTGRES_PORT}:5432"

volumes:
  postgres_data:

networks:
  vibes-network:
    external: true