# Vibesbox MCP Server - Docker Compose Configuration
# Lightweight containerized MCP server for secure command execution
# Pattern from: prps/streamlined_vibesbox/examples/docker_compose_pattern.yml

services:
  vibesbox:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: vibesbox

    # MCP server port
    # Internal: 8000, External: configurable via VIBESBOX_PORT (default 8053)
    # Avoids conflicts with Kong at 8000
    ports:
      - "${VIBESBOX_PORT:-8053}:8000"

    # Resource limits for security (prevent resource abuse)
    deploy:
      resources:
        limits:
          cpus: '0.50'      # Half a CPU core
          memory: 512M      # 512MB RAM
          pids: 100         # PID limit to prevent fork bombs

    # Security options (container hardening)
    security_opt:
      - no-new-privileges:true

    # Drop all capabilities and only add necessary ones
    cap_drop:
      - ALL
    cap_add:
      - CHOWN       # Change file ownership
      - SETGID      # Set group ID
      - SETUID      # Set user ID

    # Volume mounts
    volumes:
      - ${VIBES_PATH:-/workspace/vibes}:/workspace/vibes:rw

    # Health check for Docker monitoring
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

    # Connect to external vibes-network for inter-service communication
    networks:
      - vibes-network

    # Restart policy
    restart: unless-stopped

# Network configuration
# CRITICAL: Use external vibes-network (already created)
networks:
  vibes-network:
    external: true
