[project]
name = "agentbox"
version = "1.0.0"
description = "Alpine-based MCP server for agent command execution"
requires-python = ">=3.11"
dependencies = [
    "fastmcp>=2.0.0",
    "pydantic>=2.0.0",
    "uvicorn>=0.30.0",
]

[tool.ruff]
line-length = 120
target-version = "py311"
