services:
  mcp-vibes-server:
    build: .
    container_name: mcp-vibes-server
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${VIBES_PATH:-/workspace/vibes}:/workspace/vibes:rw
      - mcp-vibes-workspace:/workspace
    command: ["tail", "-f", "/dev/null"]

networks:
  default:
    name: mcp-network
    external: true

volumes:
  mcp-vibes-workspace:
