services:
  browserless-mcp-server:
    image: browserless/chrome:latest
    container_name: browserless-mcp-server
    restart: unless-stopped
    environment:
      # Browserless Configuration
      - BROWSERLESS_TOKEN=${BROWSERLESS_TOKEN:-}
      - MAX_CONCURRENT_SESSIONS=${MAX_CONCURRENT_SESSIONS:-10}
      - MAX_QUEUE_LENGTH=${MAX_QUEUE_LENGTH:-10}
      - CONNECTION_TIMEOUT=${CONNECTION_TIMEOUT:-30000}
      - ENABLE_API_GET=${ENABLE_API_GET:-true}
      - ENABLE_HEAP_DUMP=${ENABLE_HEAP_DUMP:-false}
      - ENABLE_DEBUG_VIEWER=${ENABLE_DEBUG_VIEWER:-false}
      - KEEP_ALIVE=${KEEP_ALIVE:-true}
      - CHROME_REFRESH_TIME=${CHROME_REFRESH_TIME:-30000}
      - PORT=9333
      
      # MCP Server Configuration
      - MCP_SERVER_NAME=browserless-mcp-server
    
    ports:
      - "9333:9333"  # Use completely different port
    
    # Resource limits for browser processes
    shm_size: 2gb
    security_opt:
      - seccomp:unconfined
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9333/pressure", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: vibes-network
    external: true
