version: '3.8'

services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    env_file:
      - ../.env
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ${DEVCONTAINER_NETWORK:-bridge}
    command: sleep infinity
    
networks:
  vibes-network:
    external: true
    name: vibes-network
    condition: service_started
