services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - vibes-devcontainer-cache:/home/vscode/.cache
      - vibes-devcontainer-go:/home/vscode/go
      - claude-auth:/home/vscode/.claude:rw
    command: sleep infinity
    working_dir: /workspace
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    user: vscode
    group_add:
      - "999"

volumes:
  vibes-devcontainer-cache:
  vibes-devcontainer-go:
  claude-auth:
