services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - vibes-network
    command: sleep infinity
    working_dir: /workspace/vibes
    
networks:
  vibes-network:
    external: true
    name: vibes-network
