services:
  basic-memory-mcp:
    build: .
    container_name: basic-memory-mcp
    image: vibes/mcp-basic-memory-server
    environment:
      - BASIC_MEMORY_DIR=/obsidian-vault
    volumes:
      # Mount Jon's Obsidian vault from iCloud
      - "/Users/jon/Library/Mobile Documents/iCloud~md~obsidian/Documents/Jon's Notebook:/obsidian-vault"
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - vibes-network
    restart: unless-stopped
    stdin_open: true
    tty: true

# Use the existing vibes network
networks:
  vibes-network:
    external: true
