services:
  # Qdrant vector database for semantic search  
  mem0_store:
    image: qdrant/qdrant
    container_name: mem0_store
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - openmemory_storage:/qdrant/storage
    networks:
      - vibes-network
    restart: unless-stopped

  # OpenMemory MCP Server (official image)
  openmemory-mcp:
    image: mem0/openmemory-mcp:latest
    container_name: openmemory-mcp
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - USER=${USER:-vibes-user}
      - QDRANT_HOST=mem0_store
      - QDRANT_PORT=6333
    depends_on:
      - mem0_store
    ports:
      - "8765:8765"
    networks:
      - vibes-network
    restart: unless-stopped

  # OpenMemory UI (official image)
  openmemory-ui:
    image: mem0/openmemory-ui:latest
    container_name: openmemory-ui
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8765
      - NEXT_PUBLIC_USER_ID=${USER:-vibes-user}
    depends_on:
      - openmemory-mcp
    ports:
      - "3000:3000"
    networks:
      - vibes-network
    restart: unless-stopped

# Use the existing vibes network
networks:
  vibes-network:
    external: true

# Persistent storage for Qdrant (fresh storage)
volumes:
  openmemory_storage:
