services:
  mcp-context7-server:
    image: vibes/mcp-context7-server:latest
    build: .
    container_name: mcp-context7-server
    restart: unless-stopped
    volumes:
      - mcp-context7-workspace:/workspace
    command: ["tail", "-f", "/dev/null"]

networks:
  default:
    name: vibes-network
    external: true

volumes:
  mcp-context7-workspace:
