services:
  github-mcp-server:
    image: ghcr.io/github/github-mcp-server:latest
    container_name: github-mcp-server
    restart: unless-stopped
    environment:
      # GitHub Authentication - set these in .env file
      - GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_PERSONAL_ACCESS_TOKEN}
      - GITHUB_APP_ID=${GITHUB_APP_ID:-}
      - GITHUB_APP_PRIVATE_KEY=${GITHUB_APP_PRIVATE_KEY:-}
      - GITHUB_APP_INSTALLATION_ID=${GITHUB_APP_INSTALLATION_ID:-}
      
      # GitHub Enterprise Server (optional)
      - GITHUB_HOST=${GITHUB_ENTERPRISE_URL:-}
      
      # MCP Server Configuration  
      - GITHUB_TOOLSETS=${GITHUB_TOOLSETS:-all}
      - GITHUB_DYNAMIC_TOOLSETS=${GITHUB_DYNAMIC_TOOLSETS:-0}
    
    ports:
      - "8081:8080"
    
    # Keep container running and ready for stdio commands
    stdin_open: true
    tty: true
    
    # Health check to ensure server is ready
    healthcheck:
      test: ["CMD", "test", "-f", "/server/github-mcp-server"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  default:
    name: vibes-network
    external: true
