
services:
  mcp-vibesbox-monitor:
    build: .
    image: vibes/mcp-vibesbox-monitor:latest
    container_name: mcp-vibesbox-monitor
    restart: unless-stopped
    ports:
      - "8090:8000"
    networks:
      - vibes-network
    volumes:
      - monitor-data:/app/data
    environment:
      - VIBESBOX_SERVER_HOST=mcp-vibesbox-server
      - VIBESBOX_SERVER_PORT=5901
      - API_HOST=0.0.0.0
      - API_PORT=8000

networks:
  vibes-network:
    external: true

volumes:
  monitor-data:
