[projects."/Users/jon/source/vibes"]
trust_level = "trusted"

# STDIO Servers (Docker-based)
[mcp_servers.vibesbox]
command = "docker"
args = ["exec", "-i", "mcp-vibesbox-server", "python3", "/workspace/server.py"]

[mcp_servers.basic_memory]
command = "docker"
args = ["exec", "-i", "basic-memory-mcp", "/app/start.sh"]

[mcp_servers.MCP_DOCKER]
command = "docker"
args = ["mcp", "gateway", "run"]

# HTTP Server (Archon) - Requires experimental flag
[mcp_servers.archon]
url = "http://localhost:8051/mcp"