services:
  mcp-vibesbox-server:
    image: vibes/mcp-vibesbox-server:latest
    build: .
    container_name: mcp-vibesbox-server
    restart: unless-stopped
    privileged: true
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_READ_SEARCH
    stop_signal: SIGRTMIN+3
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${VIBES_PATH:-/workspace/vibes}:/workspace/vibes:rw
      - mcp-vibesbox-workspace:/workspace
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    ports:
      - "5901:5901"  # VNC server (now enabled since Chromium + VNC are working)
    command: ["/sbin/init"]

networks:
  default:
    name: vibes-network
    external: true

volumes:
  mcp-vibesbox-workspace:
