services:
  mcp-vibesbox-server:
    image: vibes/mcp-vibesbox-server:latest
    build: .
    container_name: mcp-vibesbox-server
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${VIBES_PATH:-/workspace/vibes}:/workspace/vibes:rw
      - mcp-vibesbox-workspace:/workspace
    command: ["tail", "-f", "/dev/null"]
    # Future: Add port mappings for VNC access
    # ports:
    #   - "5900:5900"  # VNC server
    #   - "6080:6080"  # noVNC web interface

networks:
  default:
    name: vibes-network
    external: true

volumes:
  mcp-vibesbox-workspace:
